#服务端口号
server:
  port: 8203


#mp配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    call-setters-on-nulls: true
  mapper-locations: classpath:/mapper/*.xml

#mysql配置
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shequ-product?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root


#rabbitmq
  rabbitmq:
    host: 43.143.179.85
    port: 5672
    username: guest
    password: guest
    publisher-confirm-type: CORRELATED
    publisher-returns: true
    listener:
      simple:
        prefetch: 1
        concurrency: 3
        acknowledge-mode: manual
#jackson配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#设置上传文件的大小
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 100MB

#oss对象存储
aliyun:
  endpoint: oss-cn-beijing.aliyuncs.com
  keyid: LTAI5tNdhXTGe4ycgXaMNPVY
  keysecret: qQ0Ym0I1oyEVybomhCoYwLIBzwwVRh
  bucketname: liuqiang-ssyx-oss



