server:
  port: 8204
spring:
  application:
    name: service-sso
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 1000MB


#minio配置
minio:
  bucket: liuqiang-mv
  endpoint: http://127.0.0.1:9000
  secret-key: password
  access-key: admin
  nginxHost: http://127.0.0.1:7001
